# Generated by Django 3.1.2 on 2020-11-07 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rikishi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('master', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'heya',
                'verbose_name_plural': 'heyas',
            },
        ),
        migrations.AlterModelOptions(
            name='rikishi',
            options={'verbose_name': 'rikishi', 'verbose_name_plural': 'rikishi'},
        ),
        migrations.AddField(
            model_name='rikishi',
            name='heya',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rikishi.heya'),
        ),
    ]
